### ISSUE TITLE
Случайное обрезание длинных HTML-файлов

### ISSUE THREAD

**Issue by mkpankov** [typograf/typograf-cli#1]
Откуда проблема: типографирую результат работы Jekyll. Сам блог пост довольно длинный, а к тому же там статически делается подсветка синтаксиса в HTML.

typograf случайным образом то теряет конец файла, то работает нормально. Помимо описанного случая как минимум 3 раза в разных ситуациях файлы обрезались.

Вот архив с описываемым тут файлом:
[futures-tutorial.html.zip](https://github.com/typograf/typograf-cli/files/478355/futures-tutorial.html.zip)

```
$ cat futures-tutorial.html
<!DOCTYPE html>
<!-- Page last generated 2016-09-17 13:03:15 +0300 -->
<html lang="ru">
    <head>
...
      }
    }
  };
</script>

    </body>
</html>
$ typograf -l ru futures-tutorial.html
<!DOCTYPE html>
<!-- Page last generated 2016-09-17 13:03:15 +0300 -->
<html lang="ru">
    <head>
...
        <span class="nn">tokio_core</span><span class="p">::</span><span class="nn">io</span><span class="p">::</span><span class="nf">write_all</span><span class="p">(</span><span class="n">socket
$ ls -la futures-tutorial.html
-rw-rw-r--  1 mkpankov mkpankov   108805 сен 17 22:53 futures-tutorial.html
```

**Comment by hcodes** [comment]
Воспроизвёл в Убунте, в Windows и MacOSX проблем нет.

**Comment by mkpankov** [comment]
У меня как раз в Ubuntu проблемы, локально и на Travis.

**Comment by hcodes** [comment]
Поправил ошибку.
v2.0.0

P.S.: Потребуется Node.js 4 или выше.

**Comment by mkpankov** [comment]
@hcodes большое спасибо за оперативное исправление!
