### ISSUE TITLE
Error while trying to typograf JSON file

### ISSUE THREAD

**Issue by iksent** [typograf/typograf-cli#17]
Hello!
- I am running: `typograf -l ru ./locales/ru/landing.json`
- I am getting: `Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/typograf.titles.json' is not defined by "exports" in <project/path>/node_modules/typograf/package.json`
- I tried installing typograf-cli globally via NPM and locally in project via YARN

**Comment by hcodes** [comment]
v6.0.2
